---
# Cockpit web console configuration and management tasks
# These tasks run hourly to ensure Cockpit is properly configured

- name: "Ensure Cockpit and modules are installed"
  apt:
    name:
      - cockpit
      - cockpit-networkmanager
      - cockpit-storaged
      - cockpit-system
      - cockpit-packagekit
      - cockpit-podman
      - cockpit-machines
    state: present
    update_cache: yes

- name: "Enable and start Cockpit socket"
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes

- name: "Configure Cockpit for optimal performance"
  lineinfile:
    path: "/etc/cockpit/cockpit.conf"
    line: "{{ item }}"
    create: yes
    owner: root
    group: root
    mode: '0644'
  loop:
    - "[WebService]"
    - "Origins = https://0.0.0.0:9090 https://localhost:9090 wss://0.0.0.0:9090 wss://localhost:9090"
    - "ProtocolHeader = X-Forwarded-Proto"
    - "ForwardedForHeader = X-Forwarded-For"

- name: "Verify Cockpit service is accessible"
  wait_for:
    port: 9090
    host: localhost
    timeout: 10
  register: cockpit_accessibility
  ignore_errors: yes

- name: "Log Cockpit configuration status"
  lineinfile:
    path: "{{ validation_log }}"
    line: "{{ ansible_date_time.iso8601 }} - Cockpit configuration {{ 'verified' if cockpit_accessibility is succeeded else 'failed' }}"